### ISSUE TITLE
CF1680F Lenient Vertex Cover | Reflective-FG's Blog

### ISSUE THREAD

**Issue by Reflective-FG** [Reflective-FG/Reflective-FG.github.io#10]
https://reflective-fg.github.io/2022/05/28/CF1680F-Lenient-Vertex-Cover/ 

 DFS 树的性质。 首先注意到题面中的这一句话：  最多只能有一条边，满足两个顶点都在这个点集中。  显然，“最多只能有一条边”意思就是有 000 条或 111 条。  0 条 所以每条边都恰好只有一个顶点在点集中。 很自然想到二分图染色，每条边两个顶点颜色不同。 所以只要这个图是二分图，就一定有解。  1 条 有一条边的两个点同色，那么去掉这个边后，剩下的图一定就是一个二分图，就转化成了上一个情

**Comment by EHBoy2009** [comment]
sto FG orz
