### ISSUE TITLE
Lockdown-Daily | Reflective-FG's Blog

### ISSUE THREAD

**Issue by Reflective-FG** [Reflective-FG/Reflective-FG.github.io#9]
https://reflective-fg.github.io/2022/05/22/Lockdown-Daily/ 

 Day 0 学校没发返校通知，可能要上网课了。 为啥感冒还要隔离啊（疑惑）。 17:00 发通知了，确实返校不了了，要上网课喽。 见不到可爱的 npy 喽，在家摆烂喽。 晚上帮可爱的 hellojim 搭了一个博客（Link）。顺便做了道 trie + brouvka，不过为啥 sort 之后 brouvka 会变快啊，不是很懂。 听说好多同学都感冒了，不是很懂。不过 npy 快好了。  Day

**Comment by EHBoy2009** [comment]
哈哈哈，太强了。
